#!/bin/bash

CACHE=/tmp/hdfs-cache

sudo rm -rf $CACHE
mkdir $CACHE

docker run -it -p 50070:50070 -p 8088:8088 -p 8040:8040 \
    -v "$CACHE":/var/lib/hadoop-hdfs/cache \
    --hostname xframes-hdfs xframes-hdfs
